// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzeLdTGE27BRa1Khs2fZhmLY4Mha6rj0Q',
    appId: '1:787295161792:web:19bd0548d415dde5f74c25',
    messagingSenderId: '787295161792',
    projectId: 'donation-blood-955b2',
    authDomain: 'donation-blood-955b2.firebaseapp.com',
    storageBucket: 'donation-blood-955b2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYvpNV5uoYjtLe3vi6C5v2Kf9O6vlgR-8',
    appId: '1:787295161792:android:c875f7879f82bfbbf74c25',
    messagingSenderId: '787295161792',
    projectId: 'donation-blood-955b2',
    storageBucket: 'donation-blood-955b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLQgoL_en1ObPwV0YL3u3lBJv-bpzWp5Y',
    appId: '1:787295161792:ios:7e62c848630558a1f74c25',
    messagingSenderId: '787295161792',
    projectId: 'donation-blood-955b2',
    storageBucket: 'donation-blood-955b2.appspot.com',
    iosBundleId: 'com.example.donationBlood',
  );
}
